### PR TITLE
CONFIG: Disable Implicit Usings and Nullable

### LINKED ISSUE #23: CONFIG: Replace `DisableImplicitNamespaceImports` with `ImplicitUsings`
I saw in the project files `DisableImplicitNamespaceImports` has been used to disable implicit usings. But `DisableImplicitNamespaceImports` is for Visual Basic projects. For C# you should use `ImplicitUsings`.

```
<PropertyGroup>
  <ImplicitUsings>disable</ImplicitUsings>
</PropertyGroup>
```

Reference:

https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#disableimplicitnamespaceimports

### PR DESCRIPTION
**Pull request by Arnab-Developer**
Fixes #23

### CODE REVIEW

**Comment by hassanhabib** [comment]
@Arnab-Developer please fix conflicts

**Comment by Arnab-Developer** [comment]
@hassanhabib I have fixed the conflicts.

**Comment by hassanhabib** [comment]
> @hassanhabib I have fixed the conflicts.


@Arnab-Developer change the title to: `CONFIG: Disable Implicit Usings and Nullable`

**Comment by Arnab-Developer** [comment]
Done

**Pull request merged**
