### PR TITLE
Moved non-Xeption specific methods to extensions methods on Exception

### PR DESCRIPTION
**Pull request by ThomasArdal**
Making the methods currently available on the `Xeption` class available as extension methods on `Exception` will make it possible to utilize methods like `UpsertDataList` and `ThrowIfContainsErrors` without having to extend the `Xeption` class. This is ideal for adding data to built-in exceptions in .NET.

### CODE REVIEW

**Comment by hassanhabib** [comment]
@cjdutoit thoughts?

**Comment by cjdutoit** [comment]
> @cjdutoit thoughts?

@hassanhabib @ThomasArdal   I think this is a nice change.  

image
I think we can change the cast to Exception here, as it now has access to DataEqualsWithDetails on the new extension.  (Need to check if there were other casts that can be updated as well.)
https://github.com/ThomasArdal/Xeption/blob/663dbdd9233df335a34b5c6d721b2ba03d19866e/Xeption/Assertions/XeptionAssertions.cs#L31  


I was expecting to see updates to the unit tests.  Do we need any updates to the unit tests to reflect that the change works on exception and derived classes or is the once we like below sufficient?  

```
[Fact]
        public void ShouldThrowIfContainsErrors()
        {
            // given
            var xeption = new Xeption();
            string someKey = GetRandomMessage();
            string someValue = GetRandomMessage();

            // when
            xeption.UpsertDataList(
                key: someKey,
                value: someValue);

            // then
            Assert.Throws<Xeption>(() =>
                xeption.ThrowIfContainsErrors());
        }
```

**Comment by ThomasArdal** [comment]
@cjdutoit I've fixed the cast to `Xeption` to just use `Exception` instead.

As for the unit tests I did actually run through them to see if they needed any updates. The only thing I can think of is to create a new test class named `ExceptionTests.Logic` and then move all of the tests from `XeptionTests.Logic` that are testing the extension methods moved to `Exception`. Not sure what you prefer there? I kept the tests in the current class since the `Exception` extension methods are still in the `XeptionExtensions` class.

**Comment by cjdutoit** [comment]
I think I am happy with the test locations and the changes made.  

@hassanhabib do you think there would be value to change the existing tests to take in TheoryData and have 2 options in there: Exceptions and Xeptions?   If no value, then happy to merge.

```
        public static TheoryData TestExceptions()
        {
            return new TheoryData<Exception>()
            {
                new Exception(),
                new Xeption(),
            };
        }
```
and then

```
        [Theory]
        [MemberData(nameof(TestExceptions))]
        public void ShouldAppendListOfKeyValues(Exception inputException)
        {
                ...
        }
```

```
        [Theory]
        [MemberData(nameof(TestExceptions))]
        public void ShouldAddDataAsDictionary(Exception inputException)
        {
                ...
        }
```
```
        [Theory]
        [MemberData(nameof(TestExceptions))]
        public void ShouldAddDataAsParameters(Exception inputException)
        {
                ...
        }
```
etc.

**Comment by cjdutoit** [comment]
Hi @ThomasArdal, can you do a quick refactor on the tests to use the `[Theory]`, then we should be good to go.  Thanks

**Comment by hassanhabib** [comment]
@ThomasArdal && @cjdutoit should we also keep the original `Xeption` model for backwards compatibility?

**Comment by cjdutoit** [comment]
@hassanhabib agree.  I think we will be fine though as the namespace for the extension methods is the same as `Xeption` class, so any existing code will see still work because of the existing `using Xeptions` namespace reference which will provide access to these extension methods.  I think the current unit tests shows that as there was no refactoring needed to make it work after the change.

**Comment by hassanhabib** [comment]
@ThomasArdal sorry I merged and reverted.

We have a little problem with that approach. If we go that route, that means every single file is now going to have to know about `Xeptions` namespace.


Before:
image


After:
image

Feel free to re-open this - I think you're up to something good here.

**Comment by ThomasArdal** [comment]
In my head, people should opt-in for these methods by including the `Xeptions` namespace. But I totally see the point there.

One solution could be moving the extension methods to the `System` namespace. But it still doesn't resolve the issue that people might not even have this using added to their code.

Another approach could be to add the method signatures back to the `Xeption` class and make them proxies for the "real" methods on `XeptionExtensions`:

```csharp
public void UpsertDataList(string key, string value)
{
    XeptionExtensions.UpsertDataList(this, key, value);
}
```

This will cover all scenarios I believe. But it will require you to maintain method signatures in two places which I don't know if you want that?

**Comment by ThomasArdal** [comment]
@hassanhabib Not trying to be the annoying "any status on this one"-guy 😁 But did you consider if you want me to do the changes proposed? Or should I leave this and let the method live on `Xeption`?

**Comment by ThomasArdal** [comment]
Were these changes dropped?

**Pull request merged**
